In [1]:
import pandas_datareader as pdr

In [2]:
import datetime

In [3]:
start = datetime.datetime(2019, 1, 1)
end = datetime.datetime(2020, 1, 1)
start_date_str = str(start.date())
end_date_str = str(end.date())

In [2]:
stocks = ['MMM', 'AXP', 'AAPL', 'BA', 'CAT', 'CVX', 'CSCO', 'KO', 'DIS', 'XOM', 'GE',
          'GS', 'HD', 'IBM', 'INTC', 'JNJ', 'JPM', 'MCD', 'MRK', 'MSFT', 'NKE', 'PFE',
          'PG', 'TRV', 'UTX', 'UNH', 'VZ', 'WMT', 'GOOGL', 'AMZN','ADBE','COST','NVDA',
          'PYPL','PEP','REGN','SBUX','ADS','INFY','TGT']

In [14]:
for ticker in stocks:
    file_name = 'data/' + ticker + '_' + start_date_str + '_to_' + end_date_str + '.csv'
    print(file_name)
    data = pdr.DataReader(ticker, 'yahoo', start, end)
    print(data.shape)
    data.to_csv(file_name)

data/MMM_2019-01-01_to_2020-01-01.csv
(253, 6)
data/AXP_2019-01-01_to_2020-01-01.csv
(253, 6)
data/AAPL_2019-01-01_to_2020-01-01.csv
(253, 6)
data/BA_2019-01-01_to_2020-01-01.csv
(253, 6)
data/CAT_2019-01-01_to_2020-01-01.csv
(253, 6)
data/CVX_2019-01-01_to_2020-01-01.csv
(253, 6)
data/CSCO_2019-01-01_to_2020-01-01.csv
(253, 6)
data/KO_2019-01-01_to_2020-01-01.csv
(253, 6)
data/DIS_2019-01-01_to_2020-01-01.csv
(253, 6)
data/XOM_2019-01-01_to_2020-01-01.csv
(253, 6)
data/GE_2019-01-01_to_2020-01-01.csv
(253, 6)
data/GS_2019-01-01_to_2020-01-01.csv
(253, 6)
data/HD_2019-01-01_to_2020-01-01.csv
(253, 6)
data/IBM_2019-01-01_to_2020-01-01.csv
(253, 6)
data/INTC_2019-01-01_to_2020-01-01.csv
(253, 6)
data/JNJ_2019-01-01_to_2020-01-01.csv
(253, 6)
data/JPM_2019-01-01_to_2020-01-01.csv
(253, 6)
data/MCD_2019-01-01_to_2020-01-01.csv
(253, 6)
data/MRK_2019-01-01_to_2020-01-01.csv
(253, 6)
data/MSFT_2019-01-01_to_2020-01-01.csv
(253, 6)
data/NKE_2019-01-01_to_2020-01-01.csv
(253, 6)
data/PFE_2019-01-01_to_2020-01-01.csv
(253, 6)
data/PG_2019-01-01_to_2020-01-01.csv
(253, 6)
data/TRV_2019-01-01_to_2020-01-01.csv
(253, 6)
data/UTX_2019-01-01_to_2020-01-01.csv
(253, 6)
data/UNH_2019-01-01_to_2020-01-01.csv
(253, 6)
data/VZ_2019-01-01_to_2020-01-01.csv
(253, 6)
data/WMT_2019-01-01_to_2020-01-01.csv
(253, 6)
data/GOOGL_2019-01-01_to_2020-01-01.csv
(253, 6)
data/AMZN_2019-01-01_to_2020-01-01.csv
(253, 6)

In [15]:
import pandas as pd

In [16]:
for (i, ticker) in enumerate(stocks):
    file_name = 'data/' + ticker + '_' + start_date_str + '_to_' + end_date_str + '.csv'
    print(file_name)
    data = pd.read_csv(file_name, parse_dates=['Date'], index_col=['Date'])
    print(data.shape)
    data['Name'] = ticker
    data.to_csv(file_name)
    
    if i == 0:
        all_stocks = data
    else:
        all_stocks = all_stocks.append(data)
        
print(all_stocks.shape)
all_stocks_file_name = 'data/all_stocks_' + start_date_str + '_to_' + end_date_str + '.csv'
all_stocks.to_csv(all_stocks_file_name)

data/MMM_2019-01-01_to_2020-01-01.csv
(253, 6)
data/AXP_2019-01-01_to_2020-01-01.csv
(253, 6)
data/AAPL_2019-01-01_to_2020-01-01.csv
(253, 6)
data/BA_2019-01-01_to_2020-01-01.csv
(253, 6)
data/CAT_2019-01-01_to_2020-01-01.csv
(253, 6)
data/CVX_2019-01-01_to_2020-01-01.csv
(253, 6)
data/CSCO_2019-01-01_to_2020-01-01.csv
(253, 6)
data/KO_2019-01-01_to_2020-01-01.csv
(253, 6)
data/DIS_2019-01-01_to_2020-01-01.csv
(253, 6)
data/XOM_2019-01-01_to_2020-01-01.csv
(253, 6)
data/GE_2019-01-01_to_2020-01-01.csv
(253, 6)
data/GS_2019-01-01_to_2020-01-01.csv
(253, 6)
data/HD_2019-01-01_to_2020-01-01.csv
(253, 6)
data/IBM_2019-01-01_to_2020-01-01.csv
(253, 6)
data/INTC_2019-01-01_to_2020-01-01.csv
(253, 6)
data/JNJ_2019-01-01_to_2020-01-01.csv
(253, 6)
data/JPM_2019-01-01_to_2020-01-01.csv
(253, 6)
data/MCD_2019-01-01_to_2020-01-01.csv
(253, 6)
data/MRK_2019-01-01_to_2020-01-01.csv
(253, 6)
data/MSFT_2019-01-01_to_2020-01-01.csv
(253, 6)
data/NKE_2019-01-01_to_2020-01-01.csv
(253, 6)
data/PFE_2019-01-01_to_2020-01-01.csv
(253, 6)
data/PG_2019-01-01_to_2020-01-01.csv
(253, 6)
data/TRV_2019-01-01_to_2020-01-01.csv
(253, 6)
data/UTX_2019-01-01_to_2020-01-01.csv
(253, 6)
data/UNH_2019-01-01_to_2020-01-01.csv
(253, 6)
data/VZ_2019-01-01_to_2020-01-01.csv
(253, 6)
data/WMT_2019-01-01_to_2020-01-01.csv
(253, 6)
data/GOOGL_2019-01-01_to_2020-01-01.csv
(253, 6)
data/AMZN_2019-01-01_to_2020-01-01.csv
(253, 6)
(7590, 7)

In [17]:
print(all_stocks.shape)

(7590, 7)

In [18]:
all_stocks = pd.read_csv(all_stocks_file_name, parse_dates=['Date'], index_col=['Date'])

In [20]:
all_stocks_2019 = all_stocks.loc['2019']

In [21]:
all_stocks_2019

,High,Low,Open,Close,Volume,Adj Close,Name
Date,,,,,,,
2019-01-02,190.990005,186.699997,187.820007,190.949997,2475200.0,179.635086,MMM
2019-01-03,188.279999,182.889999,188.279999,183.759995,3358200.0,172.871124,MMM
2019-01-04,191.979996,186.029999,186.750000,191.320007,2995100.0,179.983185,MMM
2019-01-07,192.300003,188.660004,191.360001,190.880005,2162200.0,179.569214,MMM
2019-01-08,194.110001,189.580002,193.000000,191.679993,2479800.0,180.321808,MMM
...,...,...,...,...,...,...,...
2019-12-24,1795.569946,1787.579956,1793.810059,1789.209961,881300.0,1789.209961,AMZN
2019-12-26,1870.459961,1799.500000,1801.010010,1868.770020,6005400.0,1868.770020,AMZN
2019-12-27,1901.400024,1866.010010,1882.920044,1869.800049,6186600.0,1869.800049,AMZN
2019-12-30,1884.000000,1840.619995,1874.000000,1846.890015,3674700.0,1846.890015,AMZN
2019-12-31,1853.260010,1832.229980,1842.000000,1847.839966,2506500.0,1847.839966,AMZN

In [ ]:
pdr.nasdaq_trader.get_nasdaq_symbols(retry_count=1, timeout=30, pause=None)